{%- if mcu == "esp32" or mcu == "esp32s2" or mcu == "esp32s3" -%}
[target.xtensa-{{ mcu }}-none-elf]
{%- else -%}
[target.riscv32imc-unknown-none-elf]
{%- endif %}
runner = "espflash --monitor"

[build]
rustflags = [
{%- if mcu == "esp32s2" %}
  # Enable the atomic codegen option for Xtensa
  "-C", "target-feature=+s32c1i",
{% endif -%}
{% if mcu == "esp32c2" or mcu == "esp32c3" %}
  # enable the atomic codegen option for RISCV
  "-C", "target-feature=+a",
{% endif -%}

{% if mcu == "esp32s2" or mcu == "esp32c2" or mcu == "esp32c3" %}
  # Tell the `core` library that we have atomics, even though it's not
  # specified in the target definition
  "--cfg", "target_has_atomic_load_store",
  "--cfg", 'target_has_atomic_load_store="8"',
  "--cfg", 'target_has_atomic_load_store="16"',
  "--cfg", 'target_has_atomic_load_store="32"',
  "--cfg", 'target_has_atomic_load_store="ptr"',
  "--cfg", "target_has_atomic",
  "--cfg", 'target_has_atomic="8"',
  "--cfg", 'target_has_atomic="16"',
  "--cfg", 'target_has_atomic="32"',
  "--cfg", 'target_has_atomic="ptr"',
{% endif %}

{%- if mcu == "esp32" or mcu == "esp32s2" or mcu == "esp32s3" %}
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x"
{% else %}
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tlinkall.x"
{% endif -%}
]
{% if mcu == "esp32" or mcu == "esp32s2" or mcu == "esp32s3" -%}
target = "xtensa-{{ mcu }}-none-elf"
{% else -%}
target = "riscv32imc-unknown-none-elf"
{% endif %}

[unstable]
{% if alloc -%}
build-std = ["alloc", "core"]
{%- else -%}
build-std = ["core"]
{%- endif %}
